name: Scrape GMP Data and Update Frontend

on:
  schedule:
    # Mon–Fri hourly: 08:00–19:00 IST → 02:30–13:30 UTC
    - cron: "30 2 * * 1-5"
    - cron: "30 3 * * 1-5"
    - cron: "30 4 * * 1-5"
    - cron: "30 5 * * 1-5"
    - cron: "30 6 * * 1-5"
    - cron: "30 7 * * 1-5"
    - cron: "30 8 * * 1-5"
    - cron: "30 9 * * 1-5"
    - cron: "30 10 * * 1-5"
    - cron: "30 11 * * 1-5"
    - cron: "30 12 * * 1-5"
    - cron: "30 13 * * 1-5"

    # Sat–Sun once at 10:00 IST → 4:30 UTC
    - cron: "30 4 * * 6"
    - cron: "30 4 * * 0"

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies and Playwright
        run: |
          npm install
          npx playwright install --with-deps

      - name: Run Scraper
        run: |
          npx tsx scrape.ts

      - name: Clone Frontend Repo (ipo-gmp)
        run: |
          git clone https://github.com/ainstarc/ipo-gmp.git frontend

      - name: Compare and Copy if Changed
        id: compare
        run: |
          mkdir -p frontend/public/reports
          if [ ! -f frontend/public/reports/gmp.json ]; then
            echo "No existing file. Treating as first update."
            cp data/gmp.json frontend/public/reports/gmp.json
            echo "skip=false" >> $GITHUB_OUTPUT
          else
            diffResult=$(diff -q data/gmp.json frontend/public/reports/gmp.json || true)
            if [ -z "$diffResult" ]; then
              echo "No changes detected. Skipping commit."
              echo "skip=true" >> $GITHUB_OUTPUT
            else
              echo "Changes found. Updating frontend repo..."
              cp data/gmp.json frontend/public/reports/gmp.json
              echo "skip=false" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Commit & Push to Frontend
        if: steps.compare.outputs.skip == 'false'
        run: |
          cd frontend
          git config user.name "gmp-bot"
          git config user.email "actions@github.com"
          git add public/reports/gmp.json
          git commit -m "🔄 Auto-update: latest GMP data"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/ainstarc/ipo-gmp.git main
